# Generated by Django 3.1.12 on 2026-10-04 19:22

from django.db import migrations, models
import djongo.models.fields
import usuarios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', djongo.models.fields.GenericObjectIdField()),
                ('action', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('details', models.TextField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_jti', models.CharField(max_length=255, unique=True)),
                ('user_id', djongo.models.fields.GenericObjectIdField()),
                ('expire', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'RefreshToken',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('activo', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='SI', max_length=2)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('rol', djongo.models.fields.EmbeddedField(model_container=usuarios.models.Rol)),
                ('datos_profesionales', djongo.models.fields.EmbeddedField(blank=True, model_container=usuarios.models.DatosProfesionales, null=True)),
                ('antecedentes_clinicos', djongo.models.fields.EmbeddedField(blank=True, model_container=usuarios.models.AntecedentesClinicos, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
