# Generated by Django 3.1.12 on 2026-10-04 19:22

import django.core.validators
from django.db import migrations, models
import djongo.models.fields
import farmacia.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_generico', models.CharField(help_text='Principio activo (ej. Amoxicilina).', max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('presentacion', models.CharField(help_text='Forma farmacéutica (Tableta, Jarabe, Suspensión...).', max_length=100)),
                ('concentracion', models.CharField(help_text='Dosis del principio activo (ej. 500mg).', max_length=100)),
                ('lote', models.CharField(max_length=100)),
                ('fecha_vencimiento', models.DateField()),
                ('precio_unitario', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_disponible', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('requiere_receta', models.BooleanField(default=False)),
                ('interacciones', djongo.models.fields.JSONField(default=list)),
            ],
            options={
                'db_table': 'medication_catalog',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_validacion', models.CharField(help_text='Hash o código alfanumérico único para entrega en farmacia.', max_length=100, unique=True)),
                ('fecha_emision', models.DateTimeField()),
                ('registro_medico_id', djongo.models.fields.GenericObjectIdField(blank=True, help_text='Referencia a la consulta que originó la receta.', null=True)),
                ('paciente', djongo.models.fields.EmbeddedField(model_container=farmacia.models.PacienteSnapshot)),
                ('doctor', djongo.models.fields.EmbeddedField(model_container=farmacia.models.DoctorSnapshot)),
                ('medicamentos', djongo.models.fields.ArrayField(model_container=farmacia.models.MedicamentoRecetado)),
                ('estado', models.CharField(choices=[('EMITIDA', 'Emitida'), ('DISPENSADA', 'Dispensada'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='EMITIDA', max_length=20)),
                ('fecha_dispensacion', models.DateTimeField(blank=True, null=True)),
                ('dispensado_por', djongo.models.fields.EmbeddedField(blank=True, model_container=farmacia.models.DispensadoPor, null=True)),
            ],
            options={
                'db_table': 'prescriptions',
            },
        ),
    ]
